apiVersion: apps/v1
kind: Deployment
metadata:
  name: yayadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: docker.io/yahiaelalfy/postgresimage:2.5
        env:
          - name: POSTGRES_DB
            value: "yayab"
          - name: POSTGRES_USER
            value: "yaya"
          - name: POSTGRES_PASSWORD
            value: "yaya22"
        ports:
          - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: yayadb
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
